config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    resources :subcategories
  end

  resources :listings

  root 'categories#index'

  match '/help', to: 'pages#help', via: :get
  match '/faq', to: 'pages#faq', via: :get
  match '/subcategories/find_by_category', to: 'subcategories#find_by_category', via: :post

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories
  has_many :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :category
  belongs_to :subcategory

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.includes(:subcategories)
    @community = @categories[0]
    @housing = @categories[1]
    @jobs = @categories[2]
    @personals = @categories[3]
    @for_sale = @categories[4]
    @services = @categories[5]
  end

  def show
    @listings = Listing.where(category_id: params[:id])
  end



end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def new
    @listing = Listing.new
  end

  def index
    @listings = Listing.all
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def create
    @listing = Listing.new(params.require(:listing).permit(:title, :description, :city, :state, :zipcode, :category_id, :subcategory_id))
    @listing.save
    redirect_to @listing
  end


=begin
  private
  def lisiting_params
    params.require(:listing).permit(:title, :description, :city, :state, :zipcode)
  end
=end

end

app/controllers/pages_controller.rb
 class PagesController <  ApplicationController

   def help
   end

   def faq
   end

 end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController

  def show
     @listings = Listing.where(subcategory_id: params[:id])
  end

  def find_by_category
    category = Category.find(params[:category_id])
    subcategories = category.subcategories.find_all
    render json: { subcategories: subcategories }
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<!doctype html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>rlist</title>
</head>
<body>

<!-- BREADCRUMBS PATH NAV PANEL -->
<div class="row">
  <div class="large-3 medium-3 columns" >  <a href="http://localhost:3000">RList</a>  </div>
  <div class="large-3 medium-3 columns" > <h6> <a href="http://localhost:3000"> rlist > </a>  </h6> </div>
  <hr>
</div>
<!-- END BREADCRUMBS PATH NAV PANEL -->

<!-- CONTENT AREA ROW -->
<div class="row">

  <!-- MENU-NAV-BOX    LEFT  (1st COLUMN) -->
  <div class="large-3 medium-3 columns" id="menu-nav-box">
    <p>
      <br /> <%= link_to 'Post to classfieds', new_listing_path %>
      <br />my account
      <br />log out
    </p>
    <form>
      <label>Search in RList</label>
      <input type="text" placeholder="search" />
      <input type="text" placeholder="where" />
      <div class="row">
        <div class="large-12 columns">
          <select>
            <option value="community">Community</option>
            <option value="personals">Personals</option>
            <option value="services">Services</option>
            <option value="housing">Housing</option>
            <option value="for sale">For Sale</option>
            <option value="jobs">Jobs</option>
          </select>
        </div>
      </div>
      <a href="#" class="small button">SEARCH</a><br/>
    </form>
  </div>
  <!-- END MENU-NAV-BOX    LEFT  (1st COLUMN) -->


  <!-- 2nd COLUMN CONTENT AREA  (CATEGORIES AND SUBCATEGORIES) -->
  <div class="large-3 medium-3 columns">
    <%= @inspect_var %>

    <p>
      <%= link_to 'Community', category_path(@community) %>
      <% @community.subcategories.each do |sc|  %>
          <br> <%= link_to sc.name, category_subcategory_path(@community, sc) %>
      <% end %>
    </p>

    <p>
      <%= link_to 'Personals', category_path(@personals) %>
      <% @personals.subcategories.each do |sc|  %>
          <br> <%= link_to sc.name, category_subcategory_path(@personals, sc) %>
      <% end %>
    </p>

    <p>
      <%= link_to 'Services', category_path(@services) %>
      <% @services.subcategories.each do |sc|  %>
          <br> <%= link_to sc.name, category_subcategory_path(@services, sc) %>
      <% end %>
    </p>

  </div>
  <!-- END 2nd COLUMN CONTENT AREA  (CATEGORIES AND SUBCATEGORIES) -->

  <!-- 3rd COLUMN CONTENT AREA (CATEGORIES AND SUBCATS) -->
  <div class="large-3 medium-3 columns">

    <p>
      <%= link_to 'Housing', category_path(@housing) %>
      <% @housing.subcategories.each do |sc|  %>
          <br> <%= link_to sc.name, category_subcategory_path(@housing, sc) %>
      <% end %>
    </p>

    <p>
      <%= link_to 'For Sale', category_path(@for_sale) %>
      <% @for_sale.subcategories.each do |sc|  %>
          <br> <%= link_to sc.name, category_subcategory_path(@for_sale, sc) %>
      <% end %>
    </p>

  </div>
  <!-- END 3rd COLUMN CONTENT AREA (CATEGORIES AND SUBCATS)           -->


  <!-- 3rd COLUMN CONTENT AREA (CATEGORIES AND SUBCATS) -->
  <div class="large-3 medium-3 columns">
    <p>
      <%= link_to 'Jobs', category_path(@jobs) %>
      <% @jobs.subcategories.each do |sc|  %>
          <br> <%= link_to sc.name, category_subcategory_path(@jobs, sc) %>
      <% end %>
    </p>
  </div>
  <!-- END 3rd COLUMN CONTENT AREA (CATEGORIES AND SUBCATS)           -->


</div>
<!-- END CONTENT AREA ROW -->




<!--   FOOTER -->
<hr>
<footer>
  <div class="row">
    <div class="large-12 medium-12 columns">
      <p> <%= link_to 'help', help_path %> <%= link_to 'faq', faq_path %>   info static scamms </p>
    </div>
  </div>
</footer>
<!-- END OF FOOTER -->


</body>
</html>

app/views/categories/show.html.erb
<!doctype html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>show</title>
</head>
<body>

<!-- BREADCRUMBS PATH NAV PANEL -->
<div class="row">
  <div class="large-3 medium-3 columns" >  <a href="http://localhost:3000">RList</a>  </div>
  <div class="large-3 medium-3 columns" > <h6> <a href="http://localhost:3000"> rlist > </a> <a href="#"> category > show </a> </h6> </div>
  <hr>
</div>
<!-- END BREADCRUMBS PATH NAV PANEL -->

<!-- CONTENT AREA ROW -->
<div class="row">


  <!-- MENU-NAV-BOX    LEFT  (1st COLUMN) -->
  <div class="large-3 medium-3 columns" id="menu-nav-box">
    <p>
      <br />Post to classfieds
      <br />my account
      <br />log out
    </p>
    <form>
      <label>Search in RList</label>
      <input type="text" placeholder="search" />
      <input type="text" placeholder="where" />
      <div class="row">
        <div class="large-12 columns">
          <select>
            <option value="community">Community</option>
            <option value="personals">Personals</option>
            <option value="services">Services</option>
            <option value="housing">Housing</option>
            <option value="for sale">For Sale</option>
            <option value="jobs">Jobs</option>
          </select>
        </div>
      </div>
      <a href="#" class="small button">SEARCH</a><br/>
    </form>
  </div>
  <!-- END MENU-NAV-BOX    LEFT  (1st COLUMN) -->


  <!-- 2nd COLUMN CONTENT AREA  (CONTENT of SELECTED CATEGORY) -->
  <div class="large-9 medium-9 columns">
    <a href="#"> CONTENT of <%= Category.find(params['id']).name %></a>
    <br>
    <a href="#" class="button round">newest</a> <a href="#" class="button round">oldest</a> <a href="#" class="button round">lowest price</a> <a href="#" class="button round">highest price</a>


<% if @listings.present? %>
    <p>
      <% @listings.each do |listing|  %>
       <span class="rlist_date_grey">  <%= listing.created_at.strftime('%B %d, %Y') %> </span>
       ( <%= listing.city %>, <%= listing.state %>, zip: <%= listing.zipcode %> )
        <b> <%= link_to listing.title, listing  %>  </b>
    </p>
          <hr>
      <% end %>


<% else %>
        <p> No listings found! </p>
<% end %>


  </div>
  <!-- END 2nd COLUMN CONTENT AREA  (CATEGORIES AND SUBCATEGORIES) -->
</div>
<!-- END CONTENT AREA ROW -->




<!--   FOOTER -->
<hr>
<footer>
  <div class="row">
    <div class="large-12 medium-12 columns">
      <p> <%= link_to 'help', help_path %> <%= link_to 'faq' %>   info static scamms </p>
    </div>
  </div>
</footer>
<!-- END OF FOOTER -->


</body>
</html>

app/views/layout/testlayout.html.erb
<h3><b> TEST LAYOUT </b></h3>
<p> test content of layout </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listings/index.html.erb
<p> ALL LISTINGS </p>

<% @listings.each do |l| %>
ID: <%= l.id %>
Title: <%= l.title %><br>
Description: <%= l.description %><br>
City: <%= l.city %><br>
State: <%= l.state %><br>
Zipcode: <%= l.zipcode %><br>
Category_id: <%= l.category_id %><br>
Category_name: <%= Category.find(l.category_id).name %><br>
Subcategory_id: <%= l.subcategory_id %><br>
Subcategory_name: <%= Subcategory.find(l.subcategory_id).name %><br>
Created_at: <%= l.created_at %><br>
Updated_at: <%= l.updated_at %><br>
<p> ---------------------------------------------------------- </p><br>

<% end %>


<!--
    t.string   "title"
    t.text     "description"
    t.string   "city"
    t.string   "state"
    t.string   "zipcode"
    t.integer  "category_id"
    t.integer  "subcategory_id"
    t.datetime "created_at"
    t.datetime "updated_at"
-->

app/views/listings/new.html.erb
<!doctype html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>show</title>
</head>
<body>

<%= javascript_include_tag 'listings.js'  %>

<!-- BREADCRUMBS PATH NAV PANEL -->
<div class="row">
  <div class="large-3 medium-3 columns" >  <a href="http://localhost:3000">RList</a>  </div>
  <div class="large-3 medium-3 columns" > <h6> <a href="http://localhost:3000"> rlist > jobs > it > new </a>  </h6> </div>
  <hr>
</div>
<!-- END BREADCRUMBS PATH NAV PANEL -->


<!-- CONTENT AREA ROW -->
<div class="row">


  <!-- MENU-NAV-BOX    LEFT  (1st COLUMN) -->
  <div class="large-3 medium-3 columns" id="menu-nav-box">
    <p>
      <br />Post to classfieds
      <br />my account
      <br />log out
    </p>
    <form>
      <label>Search in RList</label>
      <input type="text" placeholder="search" />
      <input type="text" placeholder="where" />
      <div class="row">
        <div class="large-12 columns">
          <select>
            <option value="community">Community</option>
            <option value="personals">Personals</option>
            <option value="services">Services</option>
            <option value="housing">Housing</option>
            <option value="for sale">For Sale</option>
            <option value="jobs">Jobs</option>
          </select>
        </div>
      </div>
      <a href="#" class="small button">SEARCH</a><br/>
    </form>
  </div>
  <!-- END MENU-NAV-BOX    LEFT  (1st COLUMN) -->


  <!-- 2nd COLUMN CONTENT AREA  (CONTENT of SELECTED CATEGORY) -->
  <div class="large-9 medium-9   columns">

      <h3> <a href="#"> POST new classfied item </a> </h3>

    <%= form_for @listing do |f| %>

    <p> <%= f.label :title %>
    <%= f.text_field :title, class: "form_text_field" %> </p>
    <p><%= f.text_area :description, class: "form_text_area", placeholder: " enter description here " %> </p>
    <p><%= f.label :category_id %>
    <%= f.select :category_id, Category.all.map {|f| [f.name, f.id]}, class: "form_select" %> </p>
    <p><%= f.label :subcategory_id %>
    <%= f.select :subcategory_id, options_for_select([]) %> </p>
    <p><%= f.label :city %>
    <%= f.text_field :city, class: "form_text_field" %> </p>
    <p><%= f.label :state %>
    <%= f.text_field :state, class: "form_text_field" %> </p>
    <p><%= f.label :zipcode %>
    <%= f.text_field :zipcode, class: "form_text_field" %> </p>
    <%= f.submit %>
    <% end %>

    <br>

<!--
    t.string   "title"
    t.text     "description"
    t.string   "city"
    t.string   "state"
    t.string   "zipcode"
    t.datetime "created_at"
    t.datetime "updated_at"
-->

  </div>
  <!-- END 2nd COLUMN CONTENT AREA  (CATEGORIES AND SUBCATEGORIES) -->


</div>
<!-- END CONTENT AREA ROW -->




<!--   FOOTER -->
<hr>
<footer>
  <div class="row">
    <div class="large-12 medium-12 columns">
      <p> <%= link_to 'help', help_path %> <%= link_to 'faq' %>   info static scamms </p>
    </div>
  </div>
</footer>
<!-- END OF FOOTER -->


</body>
</html>

app/views/listings/show.html.erb
<p> LISTING </p>

ID: <%= @listing.id %> <br>
Title: <%= @listing.title %><br>
Description: <%= @listing.description %><br>
City: <%= @listing.city %><br>
State: <%= @listing.state %><br>
Zipcode: <%= @listing.zipcode %><br>
Category id: <%= @listing.category_id %> <br>
Category name: <%= Category.find(@listing.category_id).name %><br>
Subcategory id: <%= @listing.category_id %> <br>
Subcategory name: <%= Subcategory.find(@listing.subcategory_id).name %><br>
Created_at: <%= @listing.created_at %><br>
Updated_at: <%= @listing.updated_at %><br>

app/views/pages/faq.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>faq</title>
</head>
<body>

<p> This is FAQ page</p>

</body>
</html>

app/views/pages/help.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>help</title>
</head>
<body>

<p> This is help page</p>

</body>
</html>

app/views/subcategories/show.html.erb
<!doctype html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>show</title>
</head>
<body>

<!-- BREADCRUMBS PATH NAV PANEL -->
<div class="row">
  <div class="large-3 medium-3 columns" >  <a href="http://localhost:3000">RList</a>  </div>
  <div class="large-3 medium-3 columns" > <h6> <a href="http://localhost:3000"> rlist > </a> <a href="#"> subcategory > show </a> </h6> </div>
  <hr>
</div>
<!-- END BREADCRUMBS PATH NAV PANEL -->


<!-- CONTENT AREA ROW -->
<div class="row">


  <!-- MENU-NAV-BOX    LEFT  (1st COLUMN) -->
  <div class="large-3 medium-3 columns" id="menu-nav-box">
    <p>
      <br />Post to classfieds
      <br />my account
      <br />log out
    </p>
    <form>
      <label>Search in RList</label>
      <input type="text" placeholder="search" />
      <input type="text" placeholder="where" />
      <div class="row">
        <div class="large-12 columns">
          <select>
            <option value="community">Community</option>
            <option value="personals">Personals</option>
            <option value="services">Services</option>
            <option value="housing">Housing</option>
            <option value="for sale">For Sale</option>
            <option value="jobs">Jobs</option>
          </select>
        </div>
      </div>
      <a href="#" class="small button">SEARCH</a><br/>
    </form>
  </div>
  <!-- END MENU-NAV-BOX    LEFT  (1st COLUMN) -->


  <!-- 2nd COLUMN CONTENT AREA  (CONTENT of SELECTED CATEGORY) -->
  <div class="large-9 medium-9 columns">
      <a href="#"> CONTENT of <%= Subcategory.find(params['id']).name %></a>

    <br>
    <a href="#" class="button round">newest</a> <a href="#" class="button round">oldest</a> <a href="#" class="button round">lowest price</a> <a href="#" class="button round">highest price</a>


    <% if @listings.present? %>
        <p>
          <% @listings.each do |listing|  %>
              <span class="rlist_date_grey">  <%= listing.created_at.strftime('%B %d, %Y') %> </span>
              ( <%= listing.city %>, <%= listing.state %>, zip: <%= listing.zipcode %> )
              <b> <%= link_to listing.title, listing  %>  </b>
              </p>
              <hr>
          <% end %>


    <% else %>
        <p> No listings found! </p>
    <% end %>


  </div>
  <!-- END 2nd COLUMN CONTENT AREA  (CATEGORIES AND SUBCATEGORIES) -->


</div>
<!-- END CONTENT AREA ROW -->




<!--   FOOTER -->
<hr>
<footer>
  <div class="row">
    <div class="large-12 medium-12 columns">
      <p> <%= link_to 'help', help_path %> <%= link_to 'faq' %>   info static scamms </p>
    </div>
  </div>
</footer>
<!-- END OF FOOTER -->


</body>
</html>